In [54]:
## Numpy
import numpy as np # np here is Alias

In [55]:
lst = [1,2,3,4] # List can be used as collection of non homogeneous elements unlike array
arr = np.array(lst) # it will create Array from list 

In [56]:
arr

array([1, 2, 3, 4])

In [57]:
type(arr)

numpy.ndarray

In [58]:
arr.shape

(4,)

In [59]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [60]:
## 2 dimension
arr1.shape

(2, 3)

In [61]:
# Note : Number of square brackets in O/P depicts the dimension
arr1.reshape(3,2)
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [62]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [63]:
# Conversion of Tuple into Array
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [64]:
# Take one dictionary and form an array for Values

In [65]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
# To get the data type
arr1.dtype # int 32 bit

dtype('int32')

In [67]:
# Creating Array from Scratch
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.arange(1,10,2).reshape(5,1) # 2 is step size over here

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [69]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [70]:
np.arange(1,20,2) # skipping every 2nd element

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [71]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [72]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [73]:
np.arange(50,1,-2) # it will start from 50 and end at 1 and it doesn't mean arrat of shape 50,1

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [74]:
# important
np.linspace(1,20,40) # between 1 to 20 it will create 40 equally spaced elements
# linspace means linearly spaced

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [75]:
np.linspace(1,20,40).shape

(40,)

In [76]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [77]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.zeros((3,4)) # direct way of creating array of specified shape with zeros 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [80]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
# numpy by default returns floating value
np.ones((5,2,8)) # (2,8) will be 5 times....2,8 will return inner array

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [82]:
5 + np.ones((3,5)) # Broadcasting operations

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [83]:
# Identity Matrix - Diagonal Elements will be 1
np.eye(4) # 4 here means it will create 4*4 Identity Matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
np.eye(6).reshape(4,9)

array([[1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1.]])

In [85]:
np.identity(4) # same as np.eye()

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
# Random no generation(uniform Distribution) - In uniform distribution, numbers will be generated from 0 to 1
np.random.rand(2,3)

array([[0.29430991, 0.88209189, 0.47032521],
       [0.6117516 , 0.30849701, 0.58625818]])

In [87]:
# Random numbers following a normal distribution with mean=0 and standard deviation=1
np.random.randn(5,3)


array([[-0.92375989,  1.10485282, -1.39552014],
       [ 1.78086565,  0.04205536,  0.15063624],
       [-0.32286661, -0.2000888 ,  0.57758092],
       [-0.43320565, -0.60097382, -0.3786539 ],
       [-0.78393019,  0.96832816, -0.65084916]])

In [88]:
np.random.randint(1,100) # it will give one random no from 1 to 100

28

In [89]:
np.random.randint(1,100,8) # it will give 8 random number from 1 to 100 

array([97, 97, 10, 60,  8, 88, 14, 27])

In [90]:
np.random.randint(1,100,(3,4))

array([[98, 17, 87, 35],
       [83, 80, 67, 21],
       [32, 96, 67, 55]])

In [91]:
arr = np.arange(0,11)

In [92]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
# Slicing
arr[2:7]
arr[2:7:1]

array([2, 3, 4, 5, 6])

In [94]:
arr[2:7:2]

array([2, 4, 6])

In [95]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
arr[-1] # last element

10

In [97]:
arr[-1:7]

array([], dtype=int32)

In [98]:
arr[-1:7:-1] # negative indexing
# it means start from last(-1) till 7th index with interval of -1
# and the output will also be in reverse order

array([10,  9,  8])

In [99]:
# arr[-1:3] this won't work becoz by default the interval/steps is of 1
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [100]:
arr1 = np.random.randint(2,100,20).reshape(5,4)

In [101]:
arr1

array([[49, 12, 10, 31],
       [81, 70, 37, 13],
       [51, 98, 23, 31],
       [44, 69, 14, 63],
       [81,  6, 71, 78]])

In [102]:
# to extract 3 rows with all columns from above matrix
arr1[0:3,:]

array([[49, 12, 10, 31],
       [81, 70, 37, 13],
       [51, 98, 23, 31]])

In [103]:
arr1[0:3,0:3]

array([[49, 12, 10],
       [81, 70, 37],
       [51, 98, 23]])

In [104]:
arr1[3:,1:]

array([[69, 14, 63],
       [ 6, 71, 78]])

In [105]:
arr1[2:4,0:4:3] # important problem for interview

array([[51, 31],
       [44, 63]])

In [119]:
# Universal functions
arr1 = np.random.randint(1,100,(3,3))
arr2 = np.random.randint(20,100,(3,3))

In [107]:
arr1

array([[67, 12, 75],
       [15, 43, 38],
       [98, 38, 34]])

In [108]:
arr2

array([[42, 51, 90],
       [41, 22, 34],
       [60, 67, 56]])

In [109]:
arr1 + arr2

array([[109,  63, 165],
       [ 56,  65,  72],
       [158, 105,  90]])

In [110]:
arr1 * arr2

array([[2814,  612, 6750],
       [ 615,  946, 1292],
       [5880, 2546, 1904]])

In [111]:
arr1 / arr2

array([[1.5952381 , 0.23529412, 0.83333333],
       [0.36585366, 1.95454545, 1.11764706],
       [1.63333333, 0.56716418, 0.60714286]])

In [112]:
np.sqrt(arr1)

array([[8.18535277, 3.46410162, 8.66025404],
       [3.87298335, 6.55743852, 6.164414  ],
       [9.89949494, 6.164414  , 5.83095189]])

In [113]:
np.exp(arr2) # e to the power

array([[1.73927494e+18, 1.40934908e+22, 1.22040329e+39],
       [6.39843494e+17, 3.58491285e+09, 5.83461743e+14],
       [1.14200739e+26, 1.25236317e+29, 2.09165950e+24]])

In [114]:
np.log10(arr1)

array([[1.8260748 , 1.07918125, 1.87506126],
       [1.17609126, 1.63346846, 1.5797836 ],
       [1.99122608, 1.5797836 , 1.53147892]])

In [115]:
arr1 = np.arange(1,10)

In [116]:
arr1[2:] = 1000 # known as broadcasting

In [117]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [120]:
np.dot(arr1,arr2) # element wise multiplication

array([[ 3121,  7008,  4415],
       [ 5347, 12370,  6521],
       [ 5563, 13660,  6209]])

In [121]:
np.matmul(arr1,arr2)

array([[ 3121,  7008,  4415],
       [ 5347, 12370,  6521],
       [ 5563, 13660,  6209]])

In [ ]:
# 2:20 - 2:30min How to search for more commands in numpy documentation